server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/online_shop
    password: 123456qQ@
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 956227394363-pm783anre4tkrc73g2snpi3dkliut78m.apps.googleusercontent.com
#            client-secret: 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

security:
  jwt:
    token:
      secret-key: 111111
      expire-length: 86400000
      jwtCookieName: kishop

store-folder: H:/workspace/online_shopping/store-images/
store-url: http://localhost:8081/resources/